<a href="https://colab.research.google.com/github/RAGISHIVANAND/NUMPY-FILES/blob/main/INTRODUCTION_TO_NUMPY_365_DATA_SCIENCE_SCETION_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY BASICS

INSTALLING AND UPDATING PACKAGE

NUMPY COMES PRE INSTALLED IF YOU ARE USING ANACONDA OR GOOGLE COLABS:
pip install numpy

To get the latest version:pip install numpy--upgrade

# ***IMPORTING NUMPY***

In [3]:
pip install numpy

In [4]:
pip install numpy --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 45.8 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.25.1 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.25.1 which is incompatible.


In [5]:
import numpy as np


# ***USING NUMPY***

1-D array

In [6]:
array_a=np.array([1,2,3])

In [7]:
array_a

array([1, 2, 3])

2-D *array*

In [8]:
array_b=np.array([[1,2,3],[4,5,6]])

In [9]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

# ***NUMPY DOCUMENTATION***

https://numpy.org/doc/

In [10]:
np.mean (array_b,axis=0)

array([2.5, 3.5, 4.5])