# ***INSTALLATION OF NUMPY***

In [5]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
####numpy

In [7]:
import numpy as np

# ***CREATING AN NUMPY ARRAY***

In [8]:
arr = np.array([1,2,3,4,5])

# ***CHECKING DATA TYPE OF ARR VARIABLE***

In [9]:
type(arr)

numpy.ndarray

# ***TO CHECK DIMENSIONALITY***

In [10]:
arr.shape

(5,)

# ***TO CREATE  2 DIMENSIONAL DATA***

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [12]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(2, 3)

# ***Numpy creates element wise calculation***

In [15]:
b=np.arange(10)

In [ ]:
print(b)

In [17]:
b1 = b+2

In [18]:
print(b1)

[ 2  3  4  5  6  7  8  9 10 11]


# ***SINGLE ELEMENT***

In [19]:
a=np.array([2,3,4,5,6,7,8,9,10,11])

In [20]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


In [21]:
a[0]

2

In [22]:
a[1]

3

In [23]:
a[2]

4

In [24]:
a[3]

5

In [25]:
a[4]

6

# *THIS IS FORWARDING INDEX ⏫***

# ***KNOWING THE INDEX POSITION VARIABLES ⏬ ***

In [26]:
a[[0,2,4]]

array([2, 4, 6])

# ***slicing the data***

In [30]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

In [31]:
arr2[0:7:1]

array([1, 2, 3, 4, 5, 6, 7])

lot of data in terms of dimensionality

In [33]:
arr3=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [34]:
print(arr3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
arr3[0:4,0:4]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Functions coming with the numpy package when you installed

In [39]:
b= np.arange(10)

In [43]:
print(np.random.random())

0.22326582306961018


In [56]:
np.random.seed(10)
print(np.random.random())

0.771320643266746


random.randint

In [62]:
a=np.random.randint(low=1,high=10,size=4)

In [63]:
print(a)

[9 2 9 5]


important function in numpy

In [64]:
a=np.arange(30)

In [67]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


creating in matrix form

In [68]:
x=a.reshape(3,10)

In [70]:
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [71]:
y=a.reshape(1,30)

In [72]:
print(y)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29]]
